version: '3.8'

services:
  # MySQL database
  db:
    restart: always
    image: mysql:9.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # phpMyAdmin
  phpmyadmin:
    restart: always
    image: phpmyadmin:latest
    ports:
      - "8080:80"

  # Laravel backend
  php:
    container_name: backend
    restart: always
    image: conference_cms_registry/backend:1.0
    build:
      context: ../conference-cms-backend/
      dockerfile: ../conference-cms-backend/Docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../conference-cms-backend:/conference-cms-backend
    tty: true

  # React frontend
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ../conference-cms-frontend/
      dockerfile: ../conference-cms-frontend/Docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../conference-cms-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php
